name: car_price_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - anaconda-anon-usage=0.7.5
  - anaconda-auth=0.11.0
  - anaconda-cli-base=0.6.0
  - annotated-types=0.7.0
  - archspec=0.2.5
  - backports=1.0
  - backports.tarfile=1.2.0
  - boltons=25.0.0
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.1.8
  - colorama=0.4.6
  - conda=25.11.0
  - conda-anaconda-telemetry=0.3.0
  - conda-anaconda-tos=0.2.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.11.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - cpp-expected=1.3.1
  - cryptography=46.0.3
  - distro=1.9.0
  - expat=2.7.3
  - fmt=12.0.0
  - frozendict=2.4.7
  - idna=3.11
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.1
  - jaraco.functools=4.3.0
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - keyring=25.7.0
  - krb5=1.21.3
  - libarchive=3.8.2
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcurl=8.17.0
  - libcxx=21.1.6
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libiconv=1.18
  - liblapack=3.11.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmamba=2.4.0
  - libmambapy=2.4.0
  - libmpdec=4.0.0
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libsolv=0.7.35
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.6
  - lz4-c=1.10.0
  - lzo=2.10
  - markdown-it-py=4.0.0
  - mdurl=0.1.2
  - menuinst=2.4.1
  - minisom=2.3.5
  - more-itertools=10.8.0
  - msgpack-python=1.1.2
  - ncurses=6.5
  - nlohmann_json-abi=3.12.0
  - numpy=2.3.5
  - openssl=3.6.0
  - packaging=25.0
  - pip=25.3
  - pkce=1.0.3
  - platformdirs=4.5.0
  - pluggy=1.6.0
  - pybind11-abi=11
  - pycosat=0.6.6
  - pycparser=2.23
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pydantic-settings=2.12.0
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pysocks=1.7.1
  - python=3.13.9
  - python-dotenv=1.2.1
  - python.app=3
  - python_abi=3.13
  - readchar=4.2.1
  - readline=8.3
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.5
  - rich=14.2.0
  - ruamel.yaml=0.18.16
  - ruamel.yaml.clib=0.2.14
  - semver=3.0.4
  - setuptools=80.9.0
  - shellingham=1.5.4
  - simdjson=4.2.2
  - sqlite=3.51.1
  - tk=8.6.15
  - tomli=2.3.0
  - tqdm=4.67.1
  - truststore=0.10.3
  - typer=0.20.0
  - typer-slim=0.20.0
  - typer-slim-standard=0.20.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml-cpp=0.8.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
prefix: /opt/homebrew/Caskroom/miniconda/base
