name: car_price_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - altair=5.5.0=py312hca03da5_0
  - anyio=4.12.0=pyhcf101f3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py312h4409184_2
  - arrow=1.4.0=pyhcf101f3_0
  - arrow-cpp=21.0.0=h9e9184e_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.0=h79febb2_2
  - aws-c-cal=0.9.2=h79febb2_1
  - aws-c-common=0.12.4=h79febb2_0
  - aws-c-compression=0.3.1=h79febb2_2
  - aws-c-event-stream=0.5.6=h79febb2_0
  - aws-c-http=0.10.4=h79febb2_0
  - aws-c-io=0.21.4=h79febb2_0
  - aws-c-mqtt=0.13.3=h387b88a_0
  - aws-c-s3=0.8.7=h79febb2_0
  - aws-c-sdkutils=0.2.4=h79febb2_1
  - aws-checksums=0.2.7=h79febb2_1
  - aws-crt-cpp=0.34.0=hee39554_0
  - aws-sdk-cpp=1.11.638=h35fa3df_0
  - babel=2.17.0=pyhd8ed1ab_0
  - backports.zstd=1.2.0=py312h84d6f5f_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - blinker=1.9.0=py312hca03da5_1
  - brotli=1.0.9=h80987f9_9
  - brotli-bin=1.0.9=h80987f9_9
  - brotli-python=1.2.0=py312h5b255a4_0
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.12.2=hca03da5_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - category_encoders=2.9.0=pyhcf101f3_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py312h1b4d9a2_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312h84eede6_3
  - cpython=3.12.12=py312hd8ed1ab_1
  - cycler=0.12.1=pyhcf101f3_2
  - debugpy=1.8.17=py312h56d30c9_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fonttools=4.61.0=py312h5748b74_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=hce30654_0
  - gflags=2.2.2=h313beb8_1
  - gitdb=4.0.12=py312hca03da5_0
  - gitpython=3.1.45=py312hca03da5_0
  - glog=0.5.0=h313beb8_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.8.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.7.0=pyhcf101f3_0
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.5.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - kiwisolver=1.4.9=py312hd8c8125_2
  - krb5=1.21.3=h237132a_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libblas=3.11.0=4_h51639a9_openblas
  - libbrotlicommon=1.0.9=h80987f9_9
  - libbrotlidec=1.0.9=h80987f9_9
  - libbrotlienc=1.0.9=h80987f9_9
  - libcblas=3.11.0=4_hb0561ab_openblas
  - libcurl=8.16.0=h01d3526_0
  - libcxx=21.1.7=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - libgrpc=1.71.0=h62f6fdd_0
  - libidn2=2.3.4=hb68c101_1
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=4_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libpng=1.6.53=hfab5511_0
  - libprotobuf=5.29.3=h14f15fd_1
  - libre2-11=2024.07.02=h313beb8_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.1=h9a5124b_0
  - libssh2=1.11.1=h3e2b118_0
  - libthrift=0.22.0=hbe873a3_0
  - libtiff=4.7.1=h4030677_1
  - libunistring=1.3=h1799b2a_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxgboost=3.1.2=cpu_h64a644d_2
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.7=h4a912ad_0
  - llvmlite=0.46.0=py312hc82e5dd_0
  - loguru=0.7.3=pyh707e725_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.3=py312h5748b74_0
  - matplotlib=3.10.8=py312h1f38498_0
  - matplotlib-base=3.10.8=py312h605b88b_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mistune=3.1.4=pyhcf101f3_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.7.0=py312hca03da5_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.5.0=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.63.1=py312h5d8d915_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.0=h5503f6c_0
  - orc=2.2.0=hec253e6_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - pandas=2.3.3=py312h5978115_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - phik=0.12.5=py312hd8c8125_1
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - protobuf=5.29.3=py312h514c7bf_0
  - psutil=7.1.3=py312h37e1c23_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=3.1.2=cpu_pyh718b53a_2
  - pyarrow=21.0.0=py312h3f644e9_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyobjc-core=12.1=py312h19bbe71_0
  - pyobjc-framework-cocoa=12.1=py312h1de3e18_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.12=h18782d2_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.12=hd8ed1ab_1
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h5748b74_0
  - pyzmq=27.1.0=py312hd65ceae_0
  - qhull=2020.2=h420ef59_5
  - re2=2024.07.02=h48ca7d4_0
  - readline=8.2=h1d1bf99_2
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.30.0=py312h6ef9ec0_0
  - scikit-learn=1.8.0=py312h79e0ffc_0
  - scipy=1.16.3=py312ha6bbf71_1
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=80.9.0=pyhff2d567_0
  - shap=0.50.0=cpu_py312h65375c3_0
  - six=1.17.0=pyhe01879c_1
  - slicer=0.0.8=pyhd8ed1ab_0
  - smmap=5.0.2=py312hca03da5_0
  - snappy=1.2.1=h313beb8_0
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.6=py312ha11c99a_0
  - streamlit=1.52.1=py312hca03da5_0
  - tenacity=9.1.2=py312hca03da5_0
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.13=h892fb3f_3
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.3=py312h4409184_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - unicodedata2=17.0.0=py312h4409184_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.6.1=pyhd8ed1ab_0
  - utf8proc=2.6.1=h80987f9_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - xgboost=3.1.2=cpu_pyhb39878e_2
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - yaml=0.2.5=h925e9cb_3
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h5f15de7_0
  - zlib-ng=2.3.2=h248ca61_0
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - accelerate==1.12.0
      - addict==2.4.0
      - aiofiles==25.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.10.11
      - aiohttp-retry==2.8.3
      - aioice==0.10.2
      - aiortc==1.14.0
      - aiosignal==1.4.0
      - aiosqlite==0.21.0
      - annotated-types==0.7.0
      - anthropic==0.49.0
      - anyascii==0.3.3
      - apscheduler==3.11.1
      - asyncua==1.1.8
      - av==16.0.1
      - backoff==2.2.1
      - boto3==1.41.5
      - botocore==1.41.5
      - cachetools==5.5.2
      - click==8.1.8
      - coloredlogs==15.0.1
      - cryptography==46.0.3
      - cython==3.0.12
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - dnspython==2.8.0
      - docker==7.1.0
      - docopt==0.6.2
      - easyocr==1.7.2
      - einops==0.8.1
      - fastapi==0.115.14
      - filelock==3.17.0
      - flatbuffers==25.9.23
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - ftfy==6.3.1
      - google-crc32c==1.7.1
      - h5py==3.15.1
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - ifaddr==0.2.0
      - imageio==2.37.2
      - inference-exp==0.17.0
      - iniconfig==2.3.0
      - isodate==0.7.2
      - jiter==0.12.0
      - jmespath==1.0.1
      - langdetect==1.0.9
      - lazy-loader==0.4
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - networkx==3.6.1
      - ninja==1.13.0
      - num2words==0.5.14
      - numpy==2.2.6
      - nvidia-ml-py==12.575.51
      - onnx==1.20.0
      - onnxruntime==1.21.1
      - onvif-zeep-async==2.0.0
      - openai==1.109.1
      - opencv-contrib-python==4.10.0.84
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.12.0.88
      - packaging==24.2
      - paho-mqtt==1.6.1
      - peft==0.17.1
      - pillow==11.3.0
      - pluggy==1.6.0
      - prometheus-fastapi-instrumentator==6.0.0
      - propcache==0.4.1
      - py-cpuinfo==9.0.0
      - pybase64==1.0.2
      - pyclipper==1.4.0
      - pycocotools==2.0.10
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydantic-settings==2.7.1
      - pydot==2.0.0
      - pyee==13.0.0
      - pyjwt==2.10.1
      - pylibsrtp==1.0.0
      - pylogix==1.0.5
      - pymodbus==3.8.3
      - pyopenssl==25.3.0
      - pypdfium2==4.30.0
      - pytest==8.4.2
      - python-bidi==0.6.7
      - python-doctr==0.11.0
      - python-dotenv==1.0.1
      - pyvips==2.2.3
      - qrcode==8.0
      - rapidfuzz==3.14.3
      - redis==5.0.8
      - regex==2025.11.3
      - requests-file==3.0.1
      - requests-toolbelt==1.0.0
      - rf-clip==1.1
      - rf-groundingdino==0.3.0
      - rich==14.2.0
      - s3transfer==0.15.0
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - segmentation-models-pytorch==0.5.0
      - sentencepiece==0.2.1
      - shapely==2.0.7
      - shellingham==1.5.4
      - simple-pid==2.0.1
      - slack-sdk==3.33.5
      - sortedcontainers==2.4.0
      - starlette==0.46.2
      - structlog==24.4.0
      - supervision==0.27.0
      - sympy==1.14.0
      - tifffile==2025.10.16
      - timm==1.0.22
      - tldextract==5.1.3
      - tokenizers==0.22.1
      - torch==2.9.1
      - torchvision==0.24.1
      - transformers==4.57.3
      - twilio==9.3.8
      - typer==0.16.0
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzlocal==5.3.1
      - yapf==0.43.0
      - yarl==1.22.0
      - zeep==4.3.2
      - zxing-cpp==2.2.0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/car_price_env
